"""empty message

Revision ID: 3e8842407306
Revises: 
Create Date: 2023-03-12 18:55:43.133898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8842407306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=280), nullable=False),
    sa.Column('bathNum', sa.Integer(), nullable=False),
    sa.Column('bedNum', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('PropType', sa.String(length=15), nullable=True),
    sa.Column('descr', sa.String(length=800), nullable=True),
    sa.Column('photo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('propertyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
